# shared worktree-agnostic node_modules store
enableGlobalVirtualStore: true
storeDir: ../.pnpm

# many integrations expect node executables in node_modules/.bin
preferSymlinkedExecutables: true

packageExtensions:
  "eslint-config-next@*":
    dependencies:
      next: "*"
